# Numpy
## 넘파이 ndarray 개요
## ndarray의 데이터타입
## ndarray를 편리하게 생성하기-arange, zeros, ones
## ndarray의 차원과 크기를 변경하는 reshape()
## 넘파이의 ndarray 의 데이터 세트 선택하기-인덱싱(Indexing)
## 행렬의 정렬-sort()와 argsort()
## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

## 1. 넘파이 ndarray 개요
### ndarray: 넘파이의 기반 데이터 타입, 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음.

In [3]:
#넘파이 모듈 임포트, 이때 약어로 모듈을 표현해 주는 것이 관례
import numpy as np

array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)
#이때, array()함수는 ndarray로 변환하는 기능 수행
#ndarray 배열의 shape변수는 배열의 차원과 크기를 튜플 형태로 나타내줌

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

print('\n')
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


array1: 1차원, array2: 2차원, array3:  2차원


* array1은 1차원으로 3개의 데이터를 갖고 있고, array3은 2차원으로 3개의 데이터를 갖고 있음. 이는 array()함수의 인자로 파이썬의 리스트 객체가 주로 사용되는데, 리스트 []는 1차원이고 리스트의 리스트[[]]는 2차원이기때문이다.

## 2. ndarray의 데이터 타입
### 숫자 값, 문자열 값, 불 값 등 모두 가능
### 숫자형 : int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), complex 타입제공
### ndarray 내의 데이터 타입은 같은 데이터 타입만 가능

In [4]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
#ndarray내의 데이터 타입은 dtype 속성으로 확인
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


### 리스트는 서로 다른 데이터 타입을 가질 수 있음. 
### 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함.

In [5]:
#int형과 string형이 섞여 있는 리스트
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

#int형과 float형이 섞여 있는 리스트
list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


* list2는 숫자형 값 1,2가 모두 문자열 값인 '1', '2'로 변환
* list3는 int 1,2가 float64형 1.2.로 변환

### ndarray 내 데이터값의 타입 변경 astype() 메서드를 이용해 가능-> 메모리 절약

In [6]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)


[1. 2. 3.] float64


## 3. ndarray를 편리하게 생성하기-arange, zeros, ones
### arange(): 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해 줌
### zeros(): 튜플 형태의 shape값(ex)(3,2) 을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray 반환
### ones(): 튜플 형태의 shape값(ex)(3,2) 을 입력하면 모든 값을 1로 채운 해당 shape을 가진 ndarray 반환

In [9]:
#0부터 9까지의 연속 숫자 값으로 구성된 1차원 ndarray 만들기
sequence_array=np.arange(4,10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#함수 인자로 dtype을 정해주지 않는다면 디폴트로 float64형의 데이터로 채움
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[4 5 6 7 8 9]
int32 (6,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## 4. ndarray의 차원과 크기를 변경하는 reshape()

In [10]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

#지정된 사이즈 10과 맞지 않는 형태로는 변형할 수 없음
array1.reshape(4,3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
#reshape()의 인자로 -1을 적용해주는 경우!!
array1=np.arange(10)
print(array1)
#고정된 칼럼 또는 로우에 맞는 새로운 로우 또는 칼럼을 생성해 변환하라는 의미!!
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

#호환될 수 없는 형태로는 변환할 수 없음
array4=array1.reshape(-1,4)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


ValueError: cannot reshape array of size 10 into shape (4)

### -1인자는 reshape(-1,1)와 같은 형태로 자주 사용됨. 
### --> 원본이 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 ndarray로 변환됨을 보장하므로

## 5. 넘파이의 ndarray 의 데이터 세트 선택하기-인덱싱(Indexing)
### (1) 특정한 데이터만 추출

In [ ]:
#단일 값 추출
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(1,10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

#ndarray 내의 데이터값도 수정 가능
array1[0]=9
array1[8]=0
print('array1:', array1)


#다차원 ndarray에서 단일 값 추출
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])


### (2) 슬라이싱

In [13]:
array1=np.arange(1,10)
array3=array1[0:3]
print(array3)
print(type(array3))

#:기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주함
array4=array1[:3]
print(array4)

#:기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주함
array5=array1[3:]
print(array5)

#:기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주함
array6=array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [14]:
#2차원 ndarray에서 슬라이싱
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2] \n',array2d[0:2, 0:2])
print('array2d[1:3,0:3] \n',array2d[1:3, 0:3])
print('array2d[1:3,:] \n',array2d[1:3, :])
print('array2d[:,:] \n',array2d[:, :])
print('array2d[:2,1:] \n',array2d[:2, 1:])
#축 한쪽에만 슬라이싱 적용, 다른 축에는 단일 값 인덱스 적용 가능
print('array2d[:2,0] \n',array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


* 29페이지 그림 참고(참조)

### (3) 팬시 인덱싱- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 방식

In [15]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

#[0,1]인덱스 행의 2 인덱스 열 값들 반환->(0,2),(1,2) 조합
array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

#이해잘 안감
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


### (4) 불린 인덱싱- 조건 필터링과 검색을 동시에 할 수 있음, 자주 사용됨

In [16]:
array1d=np.arange(1,10)
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [17]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

* 이때 false인 인덱스 0~4는 무시하고 인덱스 [5,6,7,8]이 만들어지고 이 위치 인덱스에 해당하는 데이터 세트를 반환

In [18]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

#위의 불린 ndarray와 동일함
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


불린 인덱싱이 동작하는 단계 도식화
* step1: 필터링 조건을 []안에 기재
* step2: false 값은 무시하고true값에 해당하는 인덱스값만 저장
* step3: 저장된 인덱스 데이터 세트로 ndarray 조회

## 행렬의 정렬-sort()와 argsort()
### 행렬 정렬
### np.sort(): 넘파이에서 sort()를 호출하는 방식, 원 행렬은 유지한 채 원 행렬의 정렬된 행렬을 반환
### ndarray.sort(): 행렬 자체에서 sort()를 호출하는 방식, 원 행렬 자체를 정렬한 형태로 반환, 이 때 반환값은 None

In [19]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [20]:
#내림차순 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [21]:
#행렬이 2차원 이상일 경우, axis축 값 설정을 통해 행방향, 또는 열방향으로 정렬 수행할 수 있음
array2d=np.array([[8,12],
                 [7,1]])

sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬: \n', sort_array2d_axis1)


로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기
### np.argsort(): 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환(p35 하단 그림 참조)

In [22]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

#내림차순으로 정렬
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
### 행렬 내적(행렬 곱)
### np.dot(): 두 행렬에서 왼쪽 행렬의 행과 오른쪽 행렬의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더함

In [23]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


### 전치 행렬
### transpose()

In [24]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]
